### ISSUE TITLE
Add code coverage tracking

### ISSUE THREAD

**Issue by princjef** [xtermjs/xterm-addon-ligatures#10]
Looks like xterm.js uses coveralls. Would need to:

* [x] Add the dependency and script hooks
* [x] Enable coveralls for the repo
* [x] Add the step to the VSTS build
* [x] Add the badge

I can take care of everything but the build step
